
void main() {
//  var list1 = ["ben",1,true,"ashley","utah"];
//   var list2 = [2,6,4,7,9,0];
//   var list3 = ["ben","ashley","utah","harry"];

  
  //list1.replaceRange(2,4,["ashley",false]);
 
  
  //   list1[3]="harry";
// int a = 3;
// String b = "ben";
// double c = 2.97;
// bool d = true;
//   list3.sort();
//   print(list1);
  
//   var list5 = [];
//   if(list5.isEmpty){
//   print("Empty list found");
//   }
  
//   list5.add("ashley");
//   list5.add("ben");
//   print(list5);
//   if(list5.isNotEmpty){
// print("List is not empty");
//   }
//   list5.clear();
//   print(list5);
//   var list6=[8/,4,6,9,7,1];
//   var x = List.of(list6.reversed);
//   print(x);
//   var list7 = [12,19,-7,-2,-1,25,36];
//   list6.addAll(list7);
//   print(list6);
//   list6.sort();
//   print(list6);
  
//   list6.insert(4,50);
//   print(list6); 
  
//   var list8 = ["ashley","ben"];
//   list8.insertAll(1,["harry","utah","general elections"]);
//   print(list8);
  
//   list8.remove("general");
//   print(list8);
  
//   list8.removeAt(0);
//   print(list8);
  
//   list7.removeWhere((e) => e > 0);
//   print(list7);
  
//   list8.removeRange(2, 3);
//   print(list8);
  
//   list7.retainWhere((e) => e > 7);
//   print(list7);
  
//   Dictionary
  
//   var map1 = {1:'ben',2:'utah',4:'ashley'};
//   print(map1.length);
  
//   var map1 = {1:'ben',2:'utah',4:'ashley'};
//   map1[5] = "alan";
//   print(map1);
  
//   var map1 = {"1":'ben',2:'utah',4:'alan'};
//   map1.addAll({6:"abc",7:"fff"});
 
//   print(map1);
  
//   var students = {'12a':["ben",20,"b"],"13a":["utah",22,"a"]};
//   print(students);
  
//   var map1 = {1:'ben',2:'utah',4:'alan'};
//   map1.remove(3);
//   print(map1);
  
//   var map1 = {1:'bilal',2:'umair',4:'ali'};
//   map1.removeWhere((key, value) => value.startsWith('u'));
//   print(map1);
  
  
//   var map1 = {1:'bilal',2:'umair',4:'ali'};
//   var map2 = {3:'abc',5:'aaa'};
//   var mapp = {}..addAll(map1)..addAll(map2);
//   print(mapp);
  
//   var map1 = {1:'bilal',2:'umair',4:'ali'};
//    var map2 = {3:'abc',5:'aaa'};
//   var mapp = {...map1,...map2};
//   print(mapp);
  
//   var lst1 = [1,2,3,4,5];
//   var lst2 = ["bilal","umair","ali","aaa","bbb"];
//   var mapp = Map.fromIterables(lst1,lst2);
//   print(mapp);
  
  
//   var map1 = {1:'bilal',2:'umair',4:'ali'};
//   var abc = map1.containsKey(6);
//   print(abc);
  
//   var map1 = {1:'bilal',2:'umair',4:'ali'};
//   var abc = map1.containsValue("abccc");
//   print(abc);
  
//      var map1 = {1:'bilal',2:'umair',4:'ali'};
//       map1.forEach((key,value){
//         print('Keys are: ${key} and Values are :${value}');
//       }
      
//       );
  
  
  
  var abc = "ben";
  print('${abc}');
  
  
  }
